### ISSUE TITLE
ServerRequestInterface::getServerParams() are mixed

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#5]
For example:

 - GATEWAY_INTERFACE is a string
 - argv is an array

Options include:
 - making it a shape
 - splitting it into many methods
 - make it return a new ServerParams object with many methods

**Comment by YuryBandarchuk16** [comment]
@fredemmott I personally like the third option as it would be easier to call a getter instead of thinking about param name.

We should probably add the interface and a basic implementation which will return params values from ```$_SERVER```.  What do you think about it?

Also, according to the php-doc of the ```getServerParams()``` it says the following 

> The data IS NOT REQUIRED to originate from $_SERVER.

So that means that some users might want to extend the interface we define. How could we handle that?

**Comment by fredemmott** [comment]
> So that means that some users might want to extend the interface we define. How could we handle that?

If we take the third option, callers that need extensions can explicitly require an implementatino rather than the interface, or do an `instanceof` check - the interface does not need to define extension points.

**Comment by fredemmott** [comment]
> The data IS NOT REQUIRED to originate from $_SERVER.


I'm reading this as saying that providing fake data (e.g. for unit tests) is fine, as is supporting SAPIs that don't use $_SERVER (if any); I'm not reading it as saying we need to support arbitrary data.

> So that means that some users might want to extend the interface we define. How could we handle that?

They extend the interface, literally, and use the type system to handle it :) We dont' need to handle implementation-specific data in the interfaces, and this is a source of type issues in PSR-7.
